# Generated by Django 5.1.7 on 2025-03-29 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operationsubitem',
            name='museums',
            field=models.ManyToManyField(blank=True, related_name='museums', to='tour.museum', verbose_name='Museums'),
        ),
    ]
