# Generated by Django 5.1.7 on 2025-03-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0002_alter_operationsubitem_museums'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='reset_code',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Parola Sıfırlama Kodu'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='reset_code_created_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Parola Sıfırlama Kodu Oluşturulma Tarihi'),
        ),
    ]
