# Generated by Django 5.1.7 on 2025-04-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0004_support_supportmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehiclecost',
            name='bus_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Bus Cost'),
        ),
        migrations.AlterField(
            model_name='vehiclecost',
            name='car_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Car Cost'),
        ),
        migrations.AlterField(
            model_name='vehiclecost',
            name='midibus_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Midibus Cost'),
        ),
        migrations.AlterField(
            model_name='vehiclecost',
            name='minibus_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minibus Cost'),
        ),
        migrations.AlterField(
            model_name='vehiclecost',
            name='minivan_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Minivan Cost'),
        ),
    ]
