# Generated by Django 5.1.7 on 2025-04-07 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0005_alter_vehiclecost_bus_cost_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='operationitem',
            name='no_vehicle_guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='tour.guide', verbose_name='No Vehicle Guide'),
        ),
        migrations.AlterField(
            model_name='operationitem',
            name='item_type',
            field=models.CharField(choices=[('VEHICLE', 'Araçlı'), ('NO_VEHICLE_TOUR', 'Araçsız Tur'), ('NO_VEHICLE_ACTIVITY', 'Araçsız Aktivite'), ('NO_VEHICLE_GUIDE', 'Araçsız Rehber')], max_length=20, verbose_name='Item Type'),
        ),
    ]
