# Generated by Django 5.1.7 on 2025-04-09 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tour', '0006_operationitem_no_vehicle_guide_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operationsubitem',
            name='is_guide',
        ),
    ]
