from django.urls import path
from . import views

app_name = 'tour'  # Namespace tanımı

urlpatterns = [
    path('login/', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('password-reset/', views.password_reset_request, name='password_reset'),
    path('password-reset/confirm/<str:token>/', views.password_reset_verify, name='password_reset_confirm'),
    path('generic/<str:model>/', views.generic_list_view, name='list'),
    path('generic/<str:model>/<int:pk>/update/', views.generic_update_view, name='update'),
    path('generic/<str:model>/<int:pk>/delete/', views.generic_delete_view, name='delete'),
    path('operation/create/', views.create_operation, name='create_operation'),
    path('operation/list/', views.operation_list, name='operation_list'),
    path('operation/<int:operation_id>/customer/create/', views.create_operation_customer, name='create_operation_customer'),
    path('operation/<int:operation_id>/sales-price/create/', views.create_operation_sales_price, name='create_operation_sales_price'),
    path('operation/<int:operation_id>/item/create/', views.create_operation_item, name='create_operation_item'),
    path('operation/<int:operation_id>/item/vehicle/create/', views.create_operation_item_vehicle, name='create_operation_item_vehicle'),
    path('operation/<int:operation_id>/item/no-vehicle/create/', views.create_operation_item_no_vehicle, name='create_operation_item_no_vehicle'),
    path('operation/<int:operation_id>/item/activity/create/', views.create_operation_item_activity, name='create_operation_item_activity'),
    path('operation/sub-item/other/create/', views.create_operation_sub_item_other_price, name='create_operation_sub_item_other_price'),
    path('operation/sub-item/guide/create/', views.create_operation_sub_item_guide, name='create_operation_sub_item_guide'),
    path('operation/sub-item/hotel/create/', views.create_operation_sub_item_hotel, name='create_operation_sub_item_hotel'),
    path('operation/sub-item/museum/create/', views.create_operation_sub_item_museum, name='create_operation_sub_item_museum'),
    path('operation/sub-item/tour/create/', views.create_operation_sub_item_tour, name='create_operation_sub_item_tour'),
    path('operation/sub-item/transfer/create/', views.create_operation_sub_item_transfer, name='create_operation_sub_item_transfer'),
    path('operation/sub-item/activity/create/', views.create_operation_sub_item_activity, name='create_operation_sub_item_activity'),
    path('sms/send/', views.send_sms, name='send_sms'),
    path('operation/jobs/', views.jobs, name='jobs'),
    path('operation/sub-item/other/<int:operation_sub_item_id>/update/', views.update_operation_sub_item_other_price, name='update_operation_sub_item_other_price'),
    path('operation/sub-item/guide/<int:operation_sub_item_id>/update/', views.update_operation_sub_item_guide, name='update_operation_sub_item_guide'),
    path('operation/sub-item/hotel/<int:operation_sub_item_id>/update/', views.update_operation_sub_item_hotel, name='update_operation_sub_item_hotel'),
    path('operation/sub-item/museum/<int:operation_sub_item_id>/update/', views.update_operation_sub_item_museum, name='update_operation_sub_item_museum'),
    path('operation/sub-item/tour/<int:operation_sub_item_id>/update/', views.update_operation_sub_item_tour, name='update_operation_sub_item_tour'),
    path('operation/sub-item/transfer/<int:operation_sub_item_id>/update/', views.update_operation_sub_item_transfer, name='update_operation_sub_item_transfer'),
    path('operation/sub-item/activity/<int:operation_sub_item_id>/update/', views.update_operation_sub_item_activity, name='update_operation_sub_item_activity'),
    path('operation/item/vehicle/<int:operation_item_id>/update/', views.update_operation_item_vehicle, name='update_operation_item_vehicle'),
    path('operation/item/no-vehicle/<int:operation_item_id>/update/', views.update_operation_item_no_vehicle, name='update_operation_item_no_vehicle'),
    path('operation/item/activity/<int:operation_item_id>/update/', views.update_operation_item_activity, name='update_operation_item_activity'),
    path('operation/<int:operation_id>/update/', views.update_operation, name='update_operation'),
    path('operation/customer/<int:operation_customer_id>/update/', views.update_operation_customer, name='update_operation_customer'),
    path('operation/sales-price/<int:operation_sales_price_id>/update/', views.update_operation_sales_price, name='update_operation_sales_price'),
    path('operation/toggle/<int:operation_id>/', views.toggle_operation, name='toggle_operation'),
    path('operation/day/toggle/<int:operation_day_id>/', views.toggle_operation_day, name='toggle_operation_day'),
    path('operation/item/toggle/<int:operation_item_id>/', views.toggle_operation_item, name='toggle_operation_item'),
    path('operation/sub-item/toggle/<int:operation_sub_item_id>/', views.toggle_operation_sub_item, name='toggle_operation_sub_item'),
    path('operation/customer/toggle/<int:operation_customer_id>/', views.toggle_customer, name='toggle_customer'),
    path('operation/sales-price/toggle/<int:operation_sales_price_id>/', views.toggle_sales_price, name='toggle_sales_price'),
    path('support/create/', views.create_support, name='create_support'),
    path('support/list/', views.support_list, name='support_list'),
    path('', views.jobs),
] 